services:
  esports-app:
    build: .
    container_name: esports-app
    restart: unless-stopped
    ports:
      - "5050:5000"
    volumes:
      - ./data:/app/instance
      - ./uploads:/app/static/uploads
    environment:
      - SECRET_KEY=esports-prod-secret-key-changeme
      - DATABASE_URL=sqlite:////app/instance/tournament.db
      - FLASK_ENV=production
      - STEAM_API_KEY=C6CD0DAB30FB2A5F64CA4678CFD912B3
      - FACEIT_API_KEY=2a42a646-5999-42b6-9380-e99b7ef032af
